### ISSUE TITLE
fs: TypeError: Bad arguments

### ISSUE THREAD

**Issue by razorg** [ravelsoft/node-jinjs#12]
TypeError: Bad arguments
    at fs.js:521:10
    at ExpressEnvironment.<anonymous> (/home/razor/Documents/dev/dinetou/website/node_modules/jinjs/lib/environment.js:106:14)
    at ExpressEnvironment.trackFile (/home/razor/Documents/dev/dinetou/website/node_modules/jinjs/lib/express.js:23:64)
    at ExpressEnvironment.<anonymous> (/home/razor/Documents/dev/dinetou/website/node_modules/jinjs/lib/environment.js:140:10)
    at ExpressEnvironment.getTemplateFromString (/home/razor/Documents/dev/dinetou/website/node_modules/jinjs/lib/express.js:31:73)
    at Object.compile (/home/razor/Documents/dev/dinetou/website/node_modules/jinjs/lib/express.js:59:43)
    at Function.compile (/home/razor/Documents/dev/dinetou/website/node_modules/express/lib/view.js:64:33)
    at ServerResponse._render (/home/razor/Documents/dev/dinetou/website/node_modules/express/lib/view.js:415:18)
    at ServerResponse.render (/home/razor/Documents/dev/dinetou/website/node_modules/express/lib/view.js:316:17)
    at Router.<anonymous> (/home/razor/Documents/dev/website/views/root.js:31:7)

Node v0.4.11
express v2.4.2

this error pops up 3-4 times, and after some refreshes, it magically shows the template perfectly.
Any idea what might be going wrong?

**Comment by ceymard** [comment]
Absolutely none,

Do you know how to reproduce ?

**Comment by razorg** [comment]
hmm, i tried with a clean project but it doesnt come up. will try to reduce current project as much as possible and see.
Thank you very much.

**Comment by ceymard** [comment]
Do you still have this issue ?

**Comment by razorg** [comment]
Didn't check it out yet!
Close it and ill comment again with more info when available.

**Comment by ceymard** [comment]
Okay perfect.
