### ISSUE TITLE
combined for with else statements throws ReferenceError

### ISSUE THREAD

**Issue by razorg** [ravelsoft/node-jinjs#13]
```
<ul>
{% for user in users %}
    <li>{{ user.username|e }}</li>
{% else %}
    <li><em>no users found</em></li>
{% endfor %}
</ul>
```

sample taken from http://jinja.pocoo.org/docs/templates/ 

throws

500 ReferenceError: loop is not defined
at eval at (/home/razor/Documents/dev/dinetou/website/node_modules/jinjs/lib/environment.js:152:7)
at __for (/home/razor/Documents/dev/dinetou/website/node_modules/jinjs/lib/utils.js:52:5)
at Object.render (eval at (/home/razor/Documents/dev/dinetou/website/node_modules/jinjs/lib/environment.js:152:7))
at ServerResponse._render (/home/razor/Documents/dev/dinetou/website/node_modules/express/lib/view.js:424:21)
at ServerResponse.render (/home/razor/Documents/dev/dinetou/website/node_modules/express/lib/view.js:316:17)
at Promise. (/home/razor/Documents/dev/dinetou/website/views/root.js:51:9)
at Promise. (/home/razor/Documents/dev/dinetou/website/node_modules/mongoose/lib/mongoose/promise.js:120:8)
at Promise. (events.js:64:17)
at Promise.emit (/home/razor/Documents/dev/dinetou/website/node_modules/mongoose/lib/mongoose/promise.js:59:38)
at Promise.complete (/home/razor/Documents/dev/dinetou/website/node_modules/mongoose/lib/mongoose/promise.js:70:20)

**Comment by ceymard** [comment]
This was fixed in commit https://github.com/Ravelsoft/node-jinjs/commit/857b1a2e04be77e0dd5f48dc9fe6538d55299466

I want to look into the other issues before making a version bump.
