### ISSUE TITLE
express running, modified template cannot be rendered rightly

### ISSUE THREAD

**Issue by ghost** [ravelsoft/node-jinjs#22]
when express server is running, I modify my template. Then access the page, the errors occurred:

500 TypeError: Cannot set property '/home/jock/apps/huodongtong/app/views/layout/form_layout.html' of undefined
at /home/jock/node_modules/jinjs/lib/environment.js:159:38
at eval at (/home/jock/node_modules/jinjs/lib/environment.js:165:14)
at Object.render (eval at (/home/jock/node_modules/jinjs/lib/environment.js:165:14))
at ServerResponse._render (/home/jock/node_modules/express/lib/view.js:425:21)
at ServerResponse.render (/home/jock/node_modules/express/lib/view.js:318:17)
at Controller.render (/home/jock/node_modules/locomotive/lib/locomotive/controller.js:98:14)

But, when I restart the server, all is right again.

what's the problem? Jinjs cached something or not?

Another question, can Jinjs can persist the compiled templates into physical files?

**Comment by ceymard** [comment]
Can you give me a reliable way of reproducing the error ?

There is indeed probably a caching problem.

**Comment by kidrecursive** [comment]
Here is how to recreate the issue, he is using Locomotive, so perhaps that is the easiest way, from the command line run:

``` javascript
npm install locomotive -g
lcm create hello
cd hello
npm install
npm install jinjs
```

Then, change /config/environments/all.js to:

var express = require('express');

``` javascript
module.exports = function() {
    this.set('views', __dirname + '/../../app/views');
    this.set('view engine', 'jinjs');
    this.set('view options', {
        layout: false
    });
    this.use(express.logger());
    this.use(express.bodyParser());
    this.use(this.router);
    this.use(express.static(__dirname + '/../../public'));
};
```

Then, add 'base.html.jinjs' to '/app/views' with this in the file:

``` html
<!DOCTYPE html>
<html>
  <head>
    <title>Hello</title>
  </head>
  <body>
    {% block content %}
    {% endblock %}
  </body>
</html>
```

Then, add 'main.html.jinjs' to '/app/views/pages' with this in the file:

``` html
{% extends "base.html.jinjs" %}

{% block content %}
    <h1>{{ title }}</h1>
{% endblock %}
```

Now, start the app from the command line with:

``` javascript
lcm server
```

Then, open your browser to 'http://127.0.0.1:3000'.  The first load will work, then refresh the page, after 2-5 refreshes, you will see the error described above.  Below is the offending line, deps is the undefined property in environment.js:

``` javascript
_this.deps[__filename][path] = true;
```

**Comment by Zizzamia** [comment]
I have the same problem and for now I have solved with this solution, but I'm not certainly is the best solution.

The solution is this page https://github.com/Zizzamia/zizzamia.com/commit/688bfa702e452d47d4dc660fd97e980b2b6400ab#diff-2 .

Let me know if you find a good way. :-)

**Comment by nmcclay** [comment]
I had the same issue, and I can confirm Zizzamia's fix for environment.js seems to resolve it:

``` javascript
// Solved the problem for now, but I'm certainly not the best solution.
try {
    _this.deps[__filename][path] = true;
    return _this.getTemplate(path);
} catch (err){
    return _this.getTemplate(path);
}
```

Importing 'pwilang' didn't seem to make a difference as far as I can tell. Just needs the above fix to jinjs/lib/environment.js around line 160.

**Comment by Zizzamia** [comment]
Nice... I'm not alone in this issue :-D

**Comment by kconragan** [comment]
I'm also having the same problem and Zizzamia's patch corrects it. Thanks!
